name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Lint check (ESLint)
        run: yarn run lint-check
      - name: Style check (Prettier)
        run: yarn run format-check
      - name: Tests
        run: yarn run test
